version: '3.3'
services:
  node:
    container_name: back
    image: 'node:19-alpine'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm run dev'
    ports:
      - '3002:3002'
    volumes:
      - './src:/home/node/app'
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: staff
      DB_PASSWORD: pwd
      DB_DATABASE: birthday_project

  mysql:
    container_name: db
    image: mysql
    environment:
      MYSQL_DATABASE: birthday_project
      MYSQL_USER: staff
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "3310:3306"
